apiVersion: apps/v1
kind: Deployment
metadata:
  name: Product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Product
  template:
    metadata:
      labels:
        app: Product
    spec:
      containers:
       - name: Product
         image: docker.io/sajadkiani/Product:1.0.6
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: Productnp
spec:
  type: NodePort
  selector: 
    app: Product
  ports:
   - name:  Productnp
     port:  5002
     protocol: TCP
     targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: Product-clusterip
spec:
  type: ClusterIP
  selector:
    app: Product
  ports:
  - name: Product-port
    protocol: TCP
    port: 5002
    targetPort: 80
